/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_eh;
import control_eh.IMC;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia lima
 */
public class TelaInput extends javax.swing.JFrame {

    /**
     * Creates new form telaInicio
     */
    public TelaInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sexo = new javax.swing.ButtonGroup();
        envio = new javax.swing.JButton();
        quilos = new javax.swing.JTextField();
        metros = new javax.swing.JTextField();
        centimetros = new javax.swing.JTextField();
        altura = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        cm = new javax.swing.JLabel();
        kg = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo IMC - Erik e Henrique");
        getContentPane().setLayout(null);

        envio.setText("Calcular");
        envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioActionPerformed(evt);
            }
        });
        getContentPane().add(envio);
        envio.setBounds(70, 240, 80, 40);

        quilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quilosActionPerformed(evt);
            }
        });
        getContentPane().add(quilos);
        quilos.setBounds(30, 170, 50, 30);

        metros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metrosActionPerformed(evt);
            }
        });
        getContentPane().add(metros);
        metros.setBounds(30, 70, 50, 30);

        centimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centimetrosActionPerformed(evt);
            }
        });
        getContentPane().add(centimetros);
        centimetros.setBounds(110, 70, 50, 30);

        altura.setText("Altura:");
        getContentPane().add(altura);
        altura.setBounds(30, 50, 50, 14);

        m.setText("m ");
        getContentPane().add(m);
        m.setBounds(90, 70, 30, 30);

        cm.setText("cm");
        getContentPane().add(cm);
        cm.setBounds(170, 70, 100, 30);

        kg.setText("Kg");
        getContentPane().add(kg);
        kg.setBounds(90, 170, 40, 30);

        idade.setText("Peso:");
        getContentPane().add(idade);
        idade.setBounds(30, 150, 50, 14);

        sexo.add(masculino);
        masculino.setText("Masculino");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sexo, org.jdesktop.beansbinding.ELProperty.create("${selection.selected}"), masculino, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });
        getContentPane().add(masculino);
        masculino.setBounds(130, 150, 140, 23);

        sexo.add(feminino);
        feminino.setText("Feminino");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sexo, org.jdesktop.beansbinding.ELProperty.create("${selection.enabled}"), feminino, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        getContentPane().add(feminino);
        feminino.setBounds(130, 180, 140, 23);

        jLabel1.setText("Sexo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 130, 70, 14);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(248, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quilosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quilosActionPerformed

    private void metrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metrosActionPerformed

    private void centimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centimetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centimetrosActionPerformed

    private void envioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioActionPerformed
        try{
            int me = Integer.parseInt(metros.getText());
            try{
                int cmt = Integer.parseInt(centimetros.getText());
                float cent = (float) cmt/100;
                float tamanho = (me)+cent;
                try{
                    int pesoC = Integer.parseInt(quilos.getText());
                    boolean sexoC = false;
                    if (feminino.isSelected())
                        sexoC = false;
                    else if (masculino.isSelected())
                        sexoC = false;
                    if (Integer.parseInt(centimetros.getText())>=100 || Integer.parseInt(centimetros.getText())<0){
                        JOptionPane.showMessageDialog(null, "Centimetros inválidos, digite um número entre 0 e 99");
                    }
                    else if(Integer.parseInt(metros.getText())>=3 || Integer.parseInt(metros.getText()) <0){
                        JOptionPane.showMessageDialog(null, "Metros inválidos, digite um número entre 0 e 2");
                    }
                    else if(Integer.parseInt(quilos.getText())<=0 ||Integer.parseInt(quilos.getText())>300 ){
                        JOptionPane.showMessageDialog(null, "Peso invalido, digite um valor entre 1 e 300");
                    }
                    else if (me==0 || cmt<10){
                        JOptionPane.showMessageDialog(null, "Tamanho Inválido");
                        JOptionPane.showMessageDialog(null, "Tamanho entre 0,10cm e 2m e 99cm");
                    }
                    else{
                        IMC imc = new IMC(tamanho, pesoC, sexoC);
                        TelaOutput tela = new TelaOutput(imc);
                        tela.setVisible(true);
                        dispose();
                    }
                }
                catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Peso invalido, digite um valor acima de 0");
                }
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Centimetros inválidos, digite um número entre 0 e 99");
            }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Metros inválidos, digite um número entre 0 e 2");
        }
        
    }//GEN-LAST:event_envioActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altura;
    private javax.swing.JTextField centimetros;
    private javax.swing.JLabel cm;
    private javax.swing.JButton envio;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JLabel idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kg;
    private javax.swing.JLabel m;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField metros;
    private javax.swing.JTextField quilos;
    private javax.swing.ButtonGroup sexo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
