/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eh.telas;
import java.text.NumberFormat;
/**
 *
 * @author Familia lima
 */
public class TelaOutput extends javax.swing.JFrame {
    /**
     * Creates new form telaResultado
     */
    public TelaOutput() {
        initComponents();
        NumberFormat nf = NumberFormat.getInstance();
        nf.setMaximumFractionDigits(2);
        String resultIMC = "calculo";
        String mensagemIMC = "Mensagem";
        imcResult.setText(resultIMC);
        mensagem.setText(mensagemIMC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imcResult = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fundo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo IMC - Erik e Henrique");
        getContentPane().setLayout(null);

        imcResult.setBackground(new java.awt.Color(153, 153, 255));
        imcResult.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        imcResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imcResult.setText("0000000000000");
        getContentPane().add(imcResult);
        imcResult.setBounds(140, 60, 120, 50);

        mensagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagem.setText("Mensagem ");
        mensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(mensagem);
        mensagem.setBounds(40, 160, 320, 100);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fundo);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 60, 120, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 160, 340, 110);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seu IMC é:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Você está:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 330, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel3.setText("By: Erik Sardinha e Henrique Velardo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(4, 280, 390, 14);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOutput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel imcResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensagem;
    // End of variables declaration//GEN-END:variables
}
